### ISSUE TITLE
Wasn't sure where to ask but....

### ISSUE THREAD

**Issue by Larceniii** [themeblvd/portfolios#1]
What is the benefit of this plugin vs just making a Portfolio category of posts?

**Comment by themeblvd** [comment]
There's really no great advantage to using this other than separation. 

A lot of people just want a way to have some sort of items they can showcase, which won't be scattered through their standard ports when users are going through archives, category listings, etc. 
​
This plugin just accommodates those people by simply giving them the option.  

—
